'''
Created on Mar 9, 2026

@author: Justin Smith, Yeni Almanza
'''

PROTOCOL = "tcp"
IP_ADDRESS = "127.0.0.1"
PORT = "5555"

KEY_REQUEST_TYPE = "request_type"
KEY_FAILURE_MESSAGE = "failure_message"
EXIT_COMMAND = "exit";
KEY_STATUS = "status"
KEY_USER = "user"
KEY_USERNAME = "username"
KEY_PASSWORD = "password"
KEY_NAME = "name"

SUCCESS_STATUS = 1
BAD_MESSAGE_STATUS = -1
UNSUPPORTED_OPERATION_STATUS = -1

AUTHENTICATE_LOGIN_REQUEST_TYPE = "AUTH"
CREATE_ACCOUNT_REQUEST_TYPE      = "CREATE_ACCOUNT"
